baseurl: https://kurtfehlhauer.com/
# baseurl: localhost
title: Kurt Fehlhauer
languageCode: en-us
pagination:
  pageSize: 10
theme: PaperMod

enableInlineShortcodes: true
pygmentsUseClasses: true

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 40
    - identifier: photography
      name: Photography
      url: /photography/
      weight: 20
    - name: posts
      url: posts/
      weight: 30

params:
    profileMode:
      enabled: true
      title: "Kurt Fehlhauer"
      subtitle: "Software Engineering, Photography, etc."
      buttons:
            - name: Photography
              url: photography
            - name: Posts
              url: posts
    socialIcons:
        - name: github
          url: "https://github.com/kfehlhauer"
        - name: linkedin
          url: "https://www.linkedin.com/in/kurtfehlhauer/"
        - name: twitter
          url: "https://twitter.com/KurtFehlhauer"

    defaultTheme: dark
    disableThemeToggle: true
    ShowShareButtons: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true

outputs:
    home:
        - HTML
        - RSS
        - JSON
